# coding: utf-8

"""
    comfyui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comfy.api.models.get_prompt200_response_exec_info import GetPrompt200ResponseExecInfo

class TestGetPrompt200ResponseExecInfo(unittest.TestCase):
    """GetPrompt200ResponseExecInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPrompt200ResponseExecInfo:
        """Test GetPrompt200ResponseExecInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPrompt200ResponseExecInfo`
        """
        model = GetPrompt200ResponseExecInfo()
        if include_optional:
            return GetPrompt200ResponseExecInfo(
                queue_remaining = 56
            )
        else:
            return GetPrompt200ResponseExecInfo(
        )
        """

    def testGetPrompt200ResponseExecInfo(self):
        """Test GetPrompt200ResponseExecInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
