# coding: utf-8

"""
    comfyui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comfy.api.models.workflow_nodes_inner_size import WorkflowNodesInnerSize

class TestWorkflowNodesInnerSize(unittest.TestCase):
    """WorkflowNodesInnerSize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowNodesInnerSize:
        """Test WorkflowNodesInnerSize
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowNodesInnerSize`
        """
        model = WorkflowNodesInnerSize()
        if include_optional:
            return WorkflowNodesInnerSize(
                var_0 = 1.337,
                var_1 = 1.337
            )
        else:
            return WorkflowNodesInnerSize(
        )
        """

    def testWorkflowNodesInnerSize(self):
        """Test WorkflowNodesInnerSize"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
