# coding: utf-8

"""
    comfyui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comfy.api.models.prompt_node_inputs_value_one_of_inner import PromptNodeInputsValueOneOfInner

class TestPromptNodeInputsValueOneOfInner(unittest.TestCase):
    """PromptNodeInputsValueOneOfInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptNodeInputsValueOneOfInner:
        """Test PromptNodeInputsValueOneOfInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptNodeInputsValueOneOfInner`
        """
        model = PromptNodeInputsValueOneOfInner()
        if include_optional:
            return PromptNodeInputsValueOneOfInner(
            )
        else:
            return PromptNodeInputsValueOneOfInner(
        )
        """

    def testPromptNodeInputsValueOneOfInner(self):
        """Test PromptNodeInputsValueOneOfInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
