# coding: utf-8

"""
    comfyui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comfy.api.models.get_prompt200_response import GetPrompt200Response

class TestGetPrompt200Response(unittest.TestCase):
    """GetPrompt200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPrompt200Response:
        """Test GetPrompt200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPrompt200Response`
        """
        model = GetPrompt200Response()
        if include_optional:
            return GetPrompt200Response(
                exec_info = comfy.api.models.get_prompt_200_response_exec_info.get_prompt_200_response_exec_info(
                    queue_remaining = 56, )
            )
        else:
            return GetPrompt200Response(
        )
        """

    def testGetPrompt200Response(self):
        """Test GetPrompt200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
