# coding: utf-8

"""
    comfyui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comfy.api.models.get_history200_response_value import GetHistory200ResponseValue

class TestGetHistory200ResponseValue(unittest.TestCase):
    """GetHistory200ResponseValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetHistory200ResponseValue:
        """Test GetHistory200ResponseValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetHistory200ResponseValue`
        """
        model = GetHistory200ResponseValue()
        if include_optional:
            return GetHistory200ResponseValue(
                timestamp = 1.337,
                prompt = [
                    null
                    ],
                outputs = None
            )
        else:
            return GetHistory200ResponseValue(
        )
        """

    def testGetHistory200ResponseValue(self):
        """Test GetHistory200ResponseValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
