# coding: utf-8

"""
    comfyui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comfy.api.models.api_v1_prompts_post200_response import ApiV1PromptsPost200Response

class TestApiV1PromptsPost200Response(unittest.TestCase):
    """ApiV1PromptsPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1PromptsPost200Response:
        """Test ApiV1PromptsPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1PromptsPost200Response`
        """
        model = ApiV1PromptsPost200Response()
        if include_optional:
            return ApiV1PromptsPost200Response(
                urls = [
                    ''
                    ]
            )
        else:
            return ApiV1PromptsPost200Response(
        )
        """

    def testApiV1PromptsPost200Response(self):
        """Test ApiV1PromptsPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
