# coding: utf-8

"""
    comfyui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comfy.api.models.post_history_request import PostHistoryRequest

class TestPostHistoryRequest(unittest.TestCase):
    """PostHistoryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostHistoryRequest:
        """Test PostHistoryRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostHistoryRequest`
        """
        model = PostHistoryRequest()
        if include_optional:
            return PostHistoryRequest(
                clear = True,
                delete = [
                    56
                    ]
            )
        else:
            return PostHistoryRequest(
        )
        """

    def testPostHistoryRequest(self):
        """Test PostHistoryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
