# coding: utf-8

"""
    comfyui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comfy.api.models.node_input_required_value_inner import NodeInputRequiredValueInner

class TestNodeInputRequiredValueInner(unittest.TestCase):
    """NodeInputRequiredValueInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeInputRequiredValueInner:
        """Test NodeInputRequiredValueInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeInputRequiredValueInner`
        """
        model = NodeInputRequiredValueInner()
        if include_optional:
            return NodeInputRequiredValueInner(
                default = '',
                min = 1.337,
                max = 1.337,
                step = 1.337,
                multiline = True
            )
        else:
            return NodeInputRequiredValueInner(
        )
        """

    def testNodeInputRequiredValueInner(self):
        """Test NodeInputRequiredValueInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
