# coding: utf-8

"""
    comfyui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comfy.api.models.workflow_nodes_inner_inputs_inner import WorkflowNodesInnerInputsInner

class TestWorkflowNodesInnerInputsInner(unittest.TestCase):
    """WorkflowNodesInnerInputsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowNodesInnerInputsInner:
        """Test WorkflowNodesInnerInputsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowNodesInnerInputsInner`
        """
        model = WorkflowNodesInnerInputsInner()
        if include_optional:
            return WorkflowNodesInnerInputsInner(
                name = '',
                type = '',
                link = 56
            )
        else:
            return WorkflowNodesInnerInputsInner(
        )
        """

    def testWorkflowNodesInnerInputsInner(self):
        """Test WorkflowNodesInnerInputsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
