# coding: utf-8

"""
    comfyui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comfy.api.models.prompt_node_inputs_value import PromptNodeInputsValue

class TestPromptNodeInputsValue(unittest.TestCase):
    """PromptNodeInputsValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptNodeInputsValue:
        """Test PromptNodeInputsValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptNodeInputsValue`
        """
        model = PromptNodeInputsValue()
        if include_optional:
            return PromptNodeInputsValue(
            )
        else:
            return PromptNodeInputsValue(
        )
        """

    def testPromptNodeInputsValue(self):
        """Test PromptNodeInputsValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
